version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-python-app:latest
    volumes:
      - .:/usr/src/app
      - ./docker/vscode-extensions:/root/.vscode-server/extensions  # こちらの行を更新しました
    stdin_open: true
    tty: true
    command: /bin/bash
